#ifndef VIDEOSYNOPSIS_DETECTORSETTINGS_H
#define VIDEOSYNOPSIS_DETECTORSETTINGS_H


struct DetectorSettings {
    //bg_subtractor
    int MOG2_HISTORY = 500;
    double MOG2_VAR_THRESHOLD = 16;
};


#endif //VIDEOSYNOPSIS_DETECTORSETTINGS_H
