//
// Created by piotr on 08.08.2020.
//

#ifndef VIDEOSYNOPSIS_DETECTOROUTPUTTYPEENUM_H
#define VIDEOSYNOPSIS_DETECTOROUTPUTTYPEENUM_H

enum DetectorOutputTypeEnum{
    BG_SUBTRACTION,

    DETECTIONS
};

#endif //VIDEOSYNOPSIS_DETECTOROUTPUTTYPEENUM_H
